# [git_hooks]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""

[monorepo.packages.argocd-httproute]
path = "argocd-httproute"
include = [
    "cog.toml",
    ".github/workflows/argocd-httproute.yaml",
]

[monorepo.packages.gateway]
path = "gateway"
include = [
    "cog.toml",
    ".github/workflows/gateway.yaml",
]

[monorepo.packages.pedalion]
path = "pedalion"
include = [
    "cog.toml",
    ".github/workflows/pedalion.yaml",
]

[monorepo.packages.epibathra]
path = "epibathra"
include = [
    "cog.toml",
    ".github/workflows/epibathra.yaml",
]
