global:
  domain:
    internal: ''
    external: ''
  gateway:
    namespace: ''
    name: ''

gateway:
  className: ''

ports:
  web: ''
  websecure: ''

tls:
  internal:
    key: '' # base64-encoded PEM
    cert: '' # base64-encoded PEM
  external:
    key: '' # base64-encoded PEM
    cert: '' # base64-encoded PEM
