---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.pharos.name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.pharos.name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.pharos.name }}
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.pharos.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.pharos.name }}
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.pharos.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.pharos.name }}
    spec:
      serviceAccountName: {{ .Values.pharos.name }}
      containers:
        - name: coordinator
          image: {{ .Values.pharos.image.repository }}:{{ .Values.pharos.image.tag }}
