---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.ergata.name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.ergata.name }}
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
