---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.pedalion.name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.ergata.name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
