{{- if or .Values.ingress.domain.internal .Values.ingress.domain.external }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
spec:
  parentRefs:
    {{- if .Values.ingress.domain.internal }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway_system.name }}
      namespace: {{ .Values.gateway_system.namespace }}
      sectionName: internal
    {{- end }}
    {{- if .Values.ingress.domain.external }}
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway_system.name }}
      namespace: {{ .Values.gateway_system.namespace }}
      sectionName: external
    {{- end }}
  hostnames:
    {{- if .Values.ingress.domain.internal }}
    - {{ .Values.ingress.subdomain }}.{{ .Values.ingress.domain.internal }}
    {{- end }}
    {{- if .Values.ingress.domain.external }}
    - {{ .Values.ingress.subdomain }}.{{ .Values.ingress.domain.external }}
    {{- end }}
  rules:
    - backendRefs:
      - group: ''
        kind: Service
        name: {{ .Values.argocd.ref.name }}
        port: {{ .Values.argocd.ref.port }}
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
