---
global:
  namespace: ''

pharos:
  name: pharos
  image:
    repository: ghcr.io/katastroma/pharos
    tag: ''

phortizo:
  name: phortizo
  image:
    repository: ghcr.io/katastroma/phortizo
    tag: ''

orpheus:
  name: orpheus
  image:
    repository: ghcr.io/katastroma/orpheus
    tag: ''

stolarches:
  name: stolarches
  image:
    repository: ghcr.io/katastroma/stolarches
    tag: ''

histia:
  name: histia
  image:
    repository: ghcr.io/katastroma/histia
    tag: ''
