---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.global.pedalion.namespace }}
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/managed-by: katastroma
    app.kubernetes.io/part-of: katastroma
