name: argocd-httproute

global:
  domain:
    internal: localhost
    external: ''

  gateway:
    namespace: gateway-system
    name: default

ingress:
  subdomain: argocd

argocd:
  ref:
    name: argocd-server
    port: 80
