name: argocd-httproute

global:
  domain:
    internal: ''
    external: ''
  gateway:
    namespace: ''
    name: ''

ingress:
  subdomain: argocd

argocd:
  ref:
    name: argocd-server
    port: 80
