name: argocd-httproute

argocd:
  ref:
    name: argocd-server
    port: 80

gateway_system:
  name: default
  namespace: gateway-system

ingress:
  subdomain: argocd
  domain:
    internal: localhost
    external: ''
