name: Release ArgoCD HTTPRoute Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - .github/workflows/argocd-httproute.yaml
      - argocd-httproute/**

env:
  REGISTRY: oci://ghcr.io/katastroma-platform/phortion

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: false
      group: release-charts
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Version Bump
        id: release
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto --package argocd-httproute
          git-user: '${{ github.actor }}'
          git-user-email: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'

      - name: Package Chart
        env:
          VERSION: ${{ steps.release.outputs.version }}
        run: helm package --version ${{ env.VERSION }} argocd-httproute

      - name: Login to Registry
        run: |
          echo "${{ github.token }}" | \
          helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Chart
        env:
          VERSION: ${{ steps.release.outputs.version }}
        run: helm push argocd-httproute-${{ env.VERSION }}.tgz ${{ env.REGISTRY }}

      - name: Push bump commit and release tag
        run: git push --follow-tags
