name: Release ArgoCD HTTPRoute Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - cog.toml
      - .github/workflows/argocd-httproute.yaml
      - argocd-httproute/**

jobs:
  release:
    uses: katastroma/skeuotheke/.github/workflows/release-chart.yaml@v0
    permissions:
      contents: write
      packages: write
    with:
      chart_name: argocd-httproute
      chart_path: argocd-httproute
      package_name: argocd-httproute
      registry: oci://ghcr.io/katastroma/phortion
