name: Release Gateway Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - .github/workflows/gateway.yaml
      - gateway/**

env:
  REGISTRY: oci://ghcr.io/katastroma-platform/phortion

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: false
      group: release-charts
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'

      - name: Setup mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install

      - name: Version Bump
        id: release
        run: |
          cog bump --auto --package gateway
          VERSION=$(cog get-version --package gateway)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Package Chart
        env:
          VERSION: ${{ steps.release.outputs.version }}
        run: helm package --version ${{ env.VERSION }} gateway

      - name: Login to Registry
        run: |
          echo "${{ github.token }}" | \
          helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Chart
        env:
          VERSION: ${{ steps.release.outputs.version }}
        run: helm push gateway-${{ env.VERSION }}.tgz ${{ env.REGISTRY }}

      - name: Push bump commit and release tag
        run: git push --follow-tags
