name: Release Gateway Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - .github/workflows/gateway.yaml
      - gateway/**

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: false
      group: release-charts
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Release Chart
        uses: ./.github/actions/release-chart
        with:
          chart: gateway
