name: Release Gateway Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - cog.toml
      - .github/workflows/gateway.yaml
      - gateway/**

jobs:
  release:
    uses: katastroma-platform/skeuotheke/.github/workflows/release-chart.yaml@v0
    permissions:
      contents: write
      packages: write
    with:
      chart_name: gateway
      chart_path: gateway
      package_name: gateway
      registry: oci://ghcr.io/katastroma-platform/phortion
