name: Release Prymna Chart

on:
  workflow_dispatch:
  push:
    branches: [default]
    paths:
      - cog.toml
      - .github/workflows/prymna.yaml
      - prymna/**

jobs:
  release:
    uses: katastroma/skeuotheke/.github/workflows/release-chart.yaml@v0
    permissions:
      contents: write
      packages: write
    with:
      chart_name: prymna
      chart_path: prymna
      package_name: prymna
      registry: oci://ghcr.io/katastroma/phortion
